[[users]]
id = "hampton"
name = "Haylin Moore"
url = "https://haylinmoore.com"

[[users]]
id = "jordan"
name = "Jordan Day"
url = "https://jordane.day"

[[users]]
id = "kush"
name = "Kushagra Srivastava"
url = "https://skushagra.com"

[[users]]
id = "fcatalano"
name = "Francesco Catalano"
url = "https://www.fcatalanoanisciblog.com/"

[[users]]
id = "rporta"
name = "Rose Porta"
url = "https://roseporta.com"

[[users]]
id = "tbo"
name = "Shanyu Thibaut Juneja"
url = "https://ghast.dev"

[[users]]
id = "s3gfault"
name = "Jasmine Cai"
url = "https://s3gfault.dev"

[[users]]
id = "leon"
name = "leon332157"
url = "https://leon3321.is-a.dev"

[[users]]
id = "rpil"
name = "Roland Pilenyi"
url = "https://rpil.dev"

[[users]]
id = "squirrelly"
name = "August"
url = "https://squirrelly.glykon.cc"

[[users]]
id = "theblushirtdude"
name = "Shankar"
url = "https://shankarsubs.vercel.app/"

[[users]]
id = "mari"
name = "Mari Braun"
url = "https://beemari.com"

[[users]]
id = "khazixi"
name = "Jason"
url = "https://jsimmonds.dev"

[[users]]
id = "kodex_38"
name = "Jeevesh"
url = "https://jeeveshkrishna.com"

[[users]]
id = "timafei"
name = "Timafei"
url = "https://timafei.dev/"
