[[users]]
id = "haylin"
name = "Haylin Moore"
url = "https://hayl.in"

[[users]]
id = "jordan"
name = "Jordan Day"
url = "https://jordane.day"

[[users]]
id = "ozel"
name = "Ozel Yilmazel"
url = "https://oz03-hub.github.io/"

[[users]]
id = "kush"
name = "Kushagra Srivastava"
url = "http://www.skushagra.com"

[[users]]
id = "rporta"
name = "Rose Porta"
url = "https://roseporta.com"

[[users]]
id = "stelleron"
name = "Shreyas Donti"
url = "https://stelleron.github.io/"

[[users]]
id = "s3gfault"
name = "Jasmine"
url = "https://s3gfault.dev"

[[users]]
id = "leon"
name = "leon332157"
url = "https://leon3321.is-a.dev"

[[users]]
id = "rpil"
name = "Roland Pilenyi"
url = "https://rpil.dev"

[[users]]
id = "theblushirtdude"
name = "Shankar"
url = "https://shankarsubs.vercel.app/"

[[users]]
id = "mari"
name = "Mari Braun"
url = "https://beemari.com"

[[users]]
id = "khazixi"
name = "Jason"
url = "https://jsimmonds.dev"

[[users]]
id = "kodex_38"
name = "Jeevesh"
url = "https://jeeveshkrishna.com"

[[users]]
id = "timafei"
name = "Timafei"
url = "https://timafei.dev/"

[[users]]
id = "ptnote"
name = "Josh"
url = "https://ptnote.dev/"

[[users]]
id = "gabe"
name = "Gabriel Ford"
url = "https://gabefork.github.io/"

[[users]]
id = "adi"
name = "Aditya"
url = "https://adityanaithani.com"

[[users]]
id = "bdunahu"
name = "Benjamin"
url = "https://operationnull.com"

[[users]]
id = "iris"
name = "Iris Chen"
url = "https://irischen.dev"

[[users]]
id = "sagnikc395"
name = "Sagnik Chatterjee"
url = "https://sagnikc395.github.io"

[[users]]
id = "vishnuvardhanbr"
name = "Vishnu Vardhan Reddy"
url = "https://vishnuvardhanbr.com"

[[users]]
id = "jerin"
name = "Jerin Thomas"
url = "https://jerinthomas.in"

[[users]]
id = "devaanand19"
name = "Deva Anand"
url = "https://devaanand.com"